### ISSUE TITLE
ZIP package

### ISSUE THREAD

**Issue by Maiux92** [negan07/ancistrus#11]
Firstly I just want to say a big thanks for your work!

This is not really an issue, but in order to unpack the downloaded firmware sources, the package zip is required.

Maybe you can just add "sudo apt-get install zip" in script/hostprepare.sh

(I installed debian with the netinstall iso file, maybe on the full ISO / VMWare image is installed by default)

**Comment by negan07** [comment]
If i remember zip should be already included into debian stretch

**Comment by negan07** [comment]
in any case they're added
