### ISSUE TITLE
Original FW 1.0.1.50 to 1.0.1.54: changes

### ISSUE THREAD

**Issue by negan07** [negan07/ancistrus#13]
[diff-D7000_V50_V54.zip](https://github.com/negan07/ancistrus/files/1589993/diff-D7000_V50_V54.zip)
generated with [founddiff.sh](https://github.com/negan07/ancistrus/blob/master/scripts/founddiff.sh)

- added ntp.htm www page
- user-defined ntp server choice
- web gui cookie support (genie ?)
- telnet login (username: admin)
- some login safety fixes (gui, ftp, console)
- some www .js fixes

**Comment by infabius** [comment]
Hi man you can create a build 196?

**Comment by infabius** [comment]
The build 195 it's so great!

**Comment by phoenix1975** [comment]
You can create firmware 1.0.1.54 with the ancistrus changes

**Comment by negan07** [comment]
the build number is the commit number

working on a qos-sqm upgrade:
it's better to include it on a new build

**Comment by infabius** [comment]
Thank you so much man I wait for your updates, but a web gui made on purpose is not possible?

**Comment by negan07** [comment]
it is in the project plan

**Comment by infabius** [comment]
Well done i'll with your updates
