### ISSUE TITLE
Original FW 1.0.1.54 to 1.0.1.60: changes

### ISSUE THREAD

**Issue by BoostOver** [negan07/ancistrus#20]
http://www.downloads.netgear.com/files/GDC/D7000/D7000_FW_V1.0.1.60_1.0.1.zip

**Comment by negan07** [comment]
[diff-54-60.zip](https://github.com/negan07/ancistrus/files/1699629/diff-54-60.zip)

-) Kernel: core/net/dev: doubled free-thread buffer.
-) Mediaserver/Minidlna: Fixed some Samsung upnpsoap.
