### ISSUE TITLE
Original FW 1.0.1.60 to 1.0.1.64: changes

### ISSUE THREAD

**Issue by lentis88** [negan07/ancistrus#21]
ftp://updates1.netgear.com/d7000/ww/D7000-V1.0.1.64_1.0.1.img

[Enhancement] Improve stability with google device (chromecase device, google home device)

**Comment by negan07** [comment]
no matter differences with old .60
gpl code is equal
rc_apps equal
gui cgi is equal
maybe some other closed binary or module
