### ISSUE TITLE
snr not change

### ISSUE THREAD

**Issue by ekelon** [negan07/ancistrus#26]
hello the commands for editing snr via telnet do not work typing:

nvram set anc_snrtweak_enable = 1
nvram set snr = xx (example 25)
but any result and router restart with old snr;
with command xdslctl configure --snr = xx (example 25)
same result, router restart but snr does not change.
Any idea? Thank

**Comment by negan07** [comment]
usage is:
```
nvram set anc_dslconfprofile=own
nvram set anc_snrtweak_enable=1
nvram set snr=25
xdslctl configure
```
or:
```
anc nvram set anc_dslconfprofile own anc_snrtweak_enable 1 snr 25
nvram commit
xdslctl configure
```
forgot to set `anc_dslconfprofile` setting to `own`

**Comment by ekelon** [comment]
Thank so much, I solved the problem. With your firmware, the router is an arrow :-)
