### ISSUE TITLE
Updating packages from monolithic #272

### ISSUE THREAD

**Issue by MrZeD81** [negan07/ancistrus#28]
Hi and first of all thanks for you support on this great modem router.
I switched from last netgear firmware to your #272 monolithic upgrade.
When i performed 'opkg upgrade', after 'opkg upgrade', i got this output:
admin@D7000:$ opkg update
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/Packages.gz.
Updated source 'ancistrus-arm-D7000'.
admin@D7000:$ opkg upgrade
Upgrading opkg from 0.3.4 to 0.3.6-010 on root.
Upgrading opkg (0.3.6) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/opkg_0.3.6-010_armD7000.ipk.
To remove package debris, try `opkg remove opkg`.
To re-attempt the install, try `opkg install opkg`.
Upgrading openssh from 7.6p1 to 7.6p1-010 on root.
Upgrading openssh (7.6p1) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/openssh_7.6p1-010_armD7000.ipk.
Upgrading openvpn from 2.4.4 to 2.4.5 on root.
Upgrading openvpn (2.4.5) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/openvpn_2.4.5_armD7000.ipk.
Upgrading iproute2 from 4.10.0 to 4.16.0 on root.
Upgrading iproute2 (4.16.0) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/iproute2_4.16.0_armD7000.ipk.
Upgrading qos-sqm from 1.2.0-13.025 to 1.2.0-13.027 on root.
Upgrading qos-sqm (1.2.0) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/qos-sqm_1.2.0-13.027_armD7000.ipk.
Upgrading ancistrus-core from 0.9.4 to 1.0.4 on root.
Upgrading ancistrus-core (1.0.4) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/ancistrus-core_1.0.4_armD7000.ipk.
Configuring zlib.
Configuring ancistrus-core.
Copying conf files & init.d runlevel dirtree on ram...
Linking rc services to core on ram...
Testing rc_apps functionality... looking good
Linking rc services to core on flash...
Configuring openssh.
Configuring utelnetd.
Configuring openvpn.
Configuring iproute2.
Configuring hdparm.
Configuring smartmontools.
Configuring qos-sqm.
Type '/usr/sbin/rc_app/rc_qos help' to see the options & settings
Configuring network-test.
Collected errors:
 * open_outer: Failed to open package '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk': Failed to open '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk'
 * open_outer: Failed to open package '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk': Failed to open '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk'
 * pkg_extract_data_file_names_to_stream: Failed to extract data.tar.* from package '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk'.
 * pkg_get_installed_files: Error extracting file list from /tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk.
 * opkg_install_pkg: Failed to determine obsolete files from previously installed opkg
 * open_outer: Failed to open package '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk': Failed to open '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk'
 * open_outer: Failed to open package '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk': Failed to open '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk'
 * pkg_extract_control_files_to_dir_with_prefix: Failed to extract control.tar.* from package '/tmp/opkg/cache/dbf5e1a8ab4d5f12322daeb79931525d_opkg_0.3.6-010_armD7000.ipk'.
 * opkg_install_pkg: Failed to extract maintainer scripts for opkg. Package debris may remain!
 * create_file_stamp: Failed to open file /tmp/opkg/cache/900a80fd0eea684ff97290d1ac136e0a_openssh_7.6p1-010_armD7000.ipk.@stamp
 * opkg_validate_cached_file: Failed to create stamp for /tmp/opkg/cache/900a80fd0eea684ff97290d1ac136e0a_openssh_7.6p1-010_armD7000.ipk.
 * opkg_validate_cached_file: Failed to open cache file /tmp/opkg/cache/900a80fd0eea684ff97290d1ac136e0a_openssh_7.6p1-010_armD7000.ipk
 * opkg_install_pkg: Failed to download openssh. Perhaps you need to run 'opkg update'?
 * create_file_stamp: Failed to open file /tmp/opkg/cache/a9bd68b94150c62fc3f4fe771cc2efa8_openvpn_2.4.5_armD7000.ipk.@stamp
 * opkg_validate_cached_file: Failed to create stamp for /tmp/opkg/cache/a9bd68b94150c62fc3f4fe771cc2efa8_openvpn_2.4.5_armD7000.ipk.
 * opkg_validate_cached_file: Failed to open cache file /tmp/opkg/cache/a9bd68b94150c62fc3f4fe771cc2efa8_openvpn_2.4.5_armD7000.ipk
 * opkg_install_pkg: Failed to download openvpn. Perhaps you need to run 'opkg update'?
 * create_file_stamp: Failed to open file /tmp/opkg/cache/e96401ea15bef00db6d4012380f50d86_iproute2_4.16.0_armD7000.ipk.@stamp
 * opkg_validate_cached_file: Failed to create stamp for /tmp/opkg/cache/e96401ea15bef00db6d4012380f50d86_iproute2_4.16.0_armD7000.ipk.
 * opkg_validate_cached_file: Failed to open cache file /tmp/opkg/cache/e96401ea15bef00db6d4012380f50d86_iproute2_4.16.0_armD7000.ipk
 * opkg_install_pkg: Failed to download iproute2. Perhaps you need to run 'opkg update'?
 * create_file_stamp: Failed to open file /tmp/opkg/cache/85348b087dea1f12ccd9f8deff57d3a6_qos-sqm_1.2.0-13.027_armD7000.ipk.@stamp
 * opkg_validate_cached_file: Failed to create stamp for /tmp/opkg/cache/85348b087dea1f12ccd9f8deff57d3a6_qos-sqm_1.2.0-13.027_armD7000.ipk.
 * opkg_validate_cached_file: Failed to open cache file /tmp/opkg/cache/85348b087dea1f12ccd9f8deff57d3a6_qos-sqm_1.2.0-13.027_armD7000.ipk
 * opkg_install_pkg: Failed to download qos-sqm. Perhaps you need to run 'opkg update'?
 * create_file_stamp: Failed to open file /tmp/opkg/cache/582f32050390fafd71de1e69e3b23050_ancistrus-core_1.0.4_armD7000.ipk.@stamp
 * opkg_validate_cached_file: Failed to create stamp for /tmp/opkg/cache/582f32050390fafd71de1e69e3b23050_ancistrus-core_1.0.4_armD7000.ipk.
 * opkg_validate_cached_file: Failed to open cache file /tmp/opkg/cache/582f32050390fafd71de1e69e3b23050_ancistrus-core_1.0.4_armD7000.ipk
 * opkg_install_pkg: Failed to download ancistrus-core. Perhaps you need to run 'opkg update'?
-------------------------------------------------------------------------------------------------------
After this i re-performed 'opkg upgrade', after 'opkg upgrade', and i got this output:
admin@D7000:$ opkg update
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/Packages.gz.
Updated source 'ancistrus-arm-D7000'.
admin@D7000:$ opkg upgrade
Upgrading openssh from 7.6p1 to 7.6p1-010 on root.
Upgrading openssh (7.6p1) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/openssh_7.6p1-010_armD7000.ipk.
When finished, kill manually sshd typing: 'killall -9 sshd'
Upgrading openvpn from 2.4.4 to 2.4.5 on root.
Upgrading openvpn (2.4.5) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/openvpn_2.4.5_armD7000.ipk.
Openvpn builtin required: cannot uninstall...
To remove package debris, try `opkg remove openvpn`.
To re-attempt the install, try `opkg install openvpn`.
Upgrading iproute2 from 4.10.0 to 4.16.0 on root.
Upgrading iproute2 (4.16.0) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/iproute2_4.16.0_armD7000.ipk.
iproute2 builtin required: cannot uninstall...
To remove package debris, try `opkg remove iproute2`.
To re-attempt the install, try `opkg install iproute2`.
Upgrading qos-sqm from 1.2.0-13.025 to 1.2.0-13.027 on root.
Upgrading iproute2 (4.16.0) on root.
Upgrading qos-sqm (1.2.0) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/qos-sqm_1.2.0-13.027_armD7000.ipk.
Upgrading ancistrus-core from 0.9.4 to 1.0.4 on root.
Upgrading ancistrus-core (1.0.4) on root.
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/ancistrus-core_1.0.4_armD7000.ipk.
Reverting to original xdslctl ...
Reverting to original rc_apps ...
Ram cleanup ...
Configuring ancistrus-core.
Updating boot script ...
Updating libscnvram.so ...
Testing nvram basic functionality... looking good
Copying init.d runlevel dirtree & conf files on ram...
Linking rc services to core on ram...
Testing rc_apps functionality... looking good
Linking rc services to core on flash...
Linking xdslctl to core on flash...
Updating main web pages & styles...
Configuring openssh.
Configuring qos-sqm.
Type '/usr/sbin/rc_app/rc_qos help' to see the options & settings
Collected errors:
 * pkg_run_script: package "openvpn" prerm script returned status 1.
 * prerm_upgrade_old_pkg: prerm script for package "openvpn" failed
 * pkg_run_script: package "iproute2" prerm script returned status 1.
 * prerm_upgrade_old_pkg: prerm script for package "iproute2" failed
---------------------------------------------------------------------------------------
Do I did something wrong? 
Regards
Dario

**Comment by negan07** [comment]
same as:
https://github.com/negan07/ancistrus/issues/27

package has been mostly updated after #272 monolithic
in particular lock removal has been cleared while old packages don't

In general, when troubling with opkg, do this step:

Remove all installation references with:
`rm -rf /usr/lib/opkg/* /tmp/opkg/`
`sync`
Now no packages result installed but no package files have been removed. Proceed reinstalling:
`opkg update`
`opkg install opkg`
`opkg install ancistrus-core`
`opkg install zlib`
`opkg install openssh`
...and so on

**Comment by BoostOver** [comment]
At the end with all command "install or upgrade" i get this error:
Collected errors:
 * pkg_get_installed_files: Failed to open ///usr/lib/opkg/info/zlib.list: No such file or directory.

**Comment by negan07** [comment]
do the suggested above

**Comment by BoostOver** [comment]
Yes.
Now there is this error:
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/openvpn_2.4.5_armD7000.ipk.killall: openvpn: no process killed
Mon Apr 30 07:50:27 2018 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
Mon Apr 30 07:50:27 2018 Exiting due to fatal error
rmmod: can't unload 'tun': unknown symbol in module, or unknown parameter

And when try:
admin@D7000:$ opkg update
Downloading https://raw.githubusercontent.com/negan07/ancistrus/gh-pages/ancistrus-arm-D7000/Packages.gz.
Updated source 'ancistrus-arm-D7000'.
admin@D7000:$ opkg upgrade
Collected errors:
 * pkg_get_installed_files: Failed to open ///usr/lib/opkg/info/zlib.list: No such file or directory.

I'm on your last build 272

Thanks

**Comment by negan07** [comment]
if `/usr/lib/opkg/*` files and `/tmp/opkg/` dir all removed (status file too) no installation references remain

rerun the startup.sh

```
rm /usr/sbin/opkg /usr/lib/opkg/*
rm -rf /tmp/opkg
cd /etc
curl -k -O https://raw.githubusercontent.com/negan07/ancistrus/master/scripts/startup.sh
chmod 755 startup.sh
./startup.sh
```

**Comment by BoostOver** [comment]
Thanks, now is fine.

**Comment by negan07** [comment]
added opkg troubleshooting solutions to wiki
https://github.com/negan07/ancistrus/wiki/opkg-package#erase-all-package-reference-infos--status

> I made all negan07 said, and screens are fixed, but unfortunally, after a physical reboot, my d7000 is stuck with power red led on, and doesnt boot ;(
> How can I fix this problem ?

maybe deleted wrong files

if problem persists recovery with tftp
https://community.netgear.com/t5/DSL-Modems-Routers/D7000-R7000-bricked-after-SW-reboot/m-p/1138950#M12699

**Comment by MrZeD81** [comment]
No one of recovery system works, even the 30-30-30.
No luck at all.

**Comment by negan07** [comment]
so not bricked but locked

[nftp.zip](https://github.com/negan07/ancistrus/files/1965380/nftp.zip)

this tool is generic for netgear

power down
keep tiny reset rear button pressed with a stick
keep pressed and power on
maintain pressed until top left leds blinks
release button
run the tool (unix machine or maybe w10 shell)
answer yes to all conditions
when rebooted follow the tftp procedure above: https://github.com/negan07/ancistrus/issues/28#issuecomment-385806687

**Comment by MrZeD81** [comment]
No luck again: after nftp command on unix, old firmware was successiful uploaded, but power led still stuck on blinking white led. All firmwares tryed, but 192.168.1.1 was un-pingable, and tft2 cant reach host.

**Comment by negan07** [comment]
white blinking led means router stopped at bootloader stage

now tftp has to work
tftp server is at 192.168.1.1
no canonic ping is visible
setup local machine netcard to 192.168.1.10 255.255.255.0 gw 192.168.1.1
upload the monolithic #211 not #272 as it's too big for tftp
`tftp -i 192.168.1.1 put D7000-V1.0.1.54_1.0.1-ancistrus_negan07-build-211.img`

**Comment by MrZeD81** [comment]
Seems all works fine now! Tnx for your support and I hope to see soon new monolithic release.
Have a nice day.
P.S.: if you need a little Paypal donation, let me know :)

**Comment by negan07** [comment]
> Seems all works fine now!


will add a wiki failsafe recovery page about

> I hope to see soon new monolithic release.


monolithic 's just a snapshot: actually no differences from: original firmware+package installations

> P.S.: if you need a little Paypal donation, let me know :)


http://www.eurogroupforanimals.org/donate
and let me know
