### ISSUE TITLE
Flash monolithic firmware 370 on 272

### ISSUE THREAD

**Issue by BoostOver** [negan07/ancistrus#31]
After reboot:

Revision Author: | negan07

Email: | negan07@users.noreply.github.com

Build Revision Author Number: | 272

Building Date: | 2018-03-04 13:44 UTC
I tried twice

**Comment by BoostOver** [comment]
Now is 370.
Boh ::-)

**Comment by negan07** [comment]
this is the firefox gecko cache retain: refresh not the page but the frame inside at it will refresh content too
