### ISSUE TITLE
New Firmware  v1.0.1.66 Released: Changes

### ISSUE THREAD

**Issue by MrZeD81** [negan07/ancistrus#35]
http://www.downloads.netgear.com/files/GDC/D7000/D7000_V1.0.1.66_1.0.1.zip

**Comment by negan07** [comment]
[target_64_66.zip](https://github.com/negan07/ancistrus/files/2421574/target_64_66.zip)

Differences from 64 to 66

some tiny login and pw recovery code fixes

**Comment by lst96** [comment]
Can I update the base firmware (currently on 64) without losing the modifications or do I got to wait for the project to update?
