### ISSUE TITLE
Web GUI buttons not working

### ISSUE THREAD

**Issue by PaziHD** [negan07/ancistrus#36]
When pressing buttons on the Package Manager (or anywhere else on the custom web gui) it shows
an error similar or exactly like this in browser console:

Uncaught ReferenceError: AncstdAction is not defined
    at HTMLInputElement.onclick (anc.cgi?next_file=opkg.htm:73)

not sure what to do about this..

**Comment by negan07** [comment]
AncstdAction() is a js function

which browser ?
which browser javascript settings ?

**Comment by PaziHD** [comment]
Google Chrome, default settings.

**Comment by PaziHD** [comment]
It seems to be working now..? Chrome may have updated between then and now..
