### ISSUE TITLE
New Firmware v1.0.1.68 Released: Changes

### ISSUE THREAD

**Issue by lentis88** [negan07/ancistrus#37]
http://www.downloads.netgear.com/files/GDC/D7000/D7000_V1.0.1.68_1.0.1.zip

Fixed security issues.

**Comment by negan07** [comment]
Here's variations from 66 to 68:

[diff-D7000_V1.0.1.66_WW_src-D7000_V1.0.1.zip](https://github.com/negan07/ancistrus/files/2425640/diff-D7000_V1.0.1.66_WW_src-D7000_V1.0.1.zip)

fix for http access restriction to usb devices only
upnp minor code fix
possible variations on wlan closed code drivers
