### ISSUE TITLE
Update DSL Driver

### ISSUE THREAD

**Issue by lentis88** [negan07/ancistrus#38]
Hi, thanks for the new update.
I have updated to the new version # 370, but I can not install the updated dsl driver.
Package Manager> Update / Install Package> Select "xdsl-driver-agtef" and after "Apply" but nothing happens, stay on the same screen but without the package names.

Thanks

Edit: solved by installing Firefox, with Edge not working.

**Comment by negan07** [comment]
couldn't recreate any issue with microsoft edge

refreshing the cache and giving access granted to jscript can help as insurance
