### ISSUE TITLE
Lock failure causes script abort with qos-sqm 2.0.0

### ISSUE THREAD

**Issue by pantelis86** [negan07/ancistrus#40]

**Comment by negan07** [comment]
?

**Comment by negan07** [comment]
post the `/tmp/qos.state` content and
details & stats output of the gui

**Comment by pantelis86** [comment]
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
cat: can't open '/tmp/var/lock/qos-sqm.lock': No such file or directory
ERROR: Giving up on getting lock after 10 attempts
ERROR: This is a bug: please issue report it

**Comment by pantelis86** [comment]
http://www.dslreports.com/speedtest/42597790

**Comment by pantelis86** [comment]
Version sqm 1.2.4 

---- qdisc ----
--- EGRESS ---
qdisc htb 1: root refcnt 2 r2q 10 default 41405 direct_packets_stat 0
 Sent 49279268 bytes 316879 pkt (dropped 0, overlimits 29118 requeues 0) 
 backlog 0b 0p requeues 0
qdisc fq_codel 110: parent 1:11 limit 1001p flows 1024 quantum 300 target 5.0ms interval 100.0ms ecn 
 Sent 49279268 bytes 316879 pkt (dropped 868, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 1524 drop_overlimit 0 new_flow_count 36702 ecn_mark 0
  new_flows_len 1 old_flows_len 13
qdisc ingress ffff: parent ffff:fff1 ---------------- 
 Sent 859712511 bytes 596899 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
--- INGRESS ---
qdisc htb 1: root refcnt 2 r2q 10 default 41405 direct_packets_stat 0
 Sent 898751332 bytes 595898 pkt (dropped 0, overlimits 75767 requeues 0) 
 backlog 0b 0p requeues 0
qdisc fq_codel 110: parent 1:11 limit 1001p flows 1024 quantum 500 target 5.0ms interval 100.0ms ecn 
 Sent 720 bytes 4 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 256 drop_overlimit 0 new_flow_count 1 ecn_mark 0
  new_flows_len 0 old_flows_len 1
qdisc fq_codel 120: parent 1:12 limit 1001p flows 1024 quantum 1500 target 5.0ms interval 100.0ms ecn 
 Sent 898750612 bytes 595894 pkt (dropped 1001, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 1560 drop_overlimit 0 new_flow_count 27960 ecn_mark 0
  new_flows_len 1 old_flows_len 9
qdisc fq_codel 130: parent 1:13 limit 1001p flows 1024 quantum 300 target 5.0ms interval 100.0ms ecn 
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  maxpacket 256 drop_overlimit 0 new_flow_count 0 ecn_mark 0
  new_flows_len 0 old_flows_len 0

---- class ----
--- EGRESS ---
class htb 1:11 parent 1:1 leaf 110: prio 0 rate 5035Kbit ceil 5035Kbit burst 2.91309Kb cburst 2.91309Kb 
 Sent 50585024 bytes 317747 pkt (dropped 0, overlimits 0 requeues 0) 
 rate 52632bit 44ppsbacklog 0b 0p requeues 0
 lended: 316879 borrowed: 0 giants: 0
 tokens: 72297 ctokens: 72297

class htb 1:1 root rate 5035Kbit ceil 5035Kbit burst 2.91309Kb cburst 2.91309Kb 
 Sent 49279268 bytes 316879 pkt (dropped 0, overlimits 0 requeues 0) 
 rate 51464bit 44ppsbacklog 0b 0p requeues 0
 lended: 0 borrowed: 0 giants: 0
 tokens: 72297 ctokens: 72297

class fq_codel 110:2e parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 136 count 0 lastcount 0 ldelay 3us
class fq_codel 110:85 parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 3us
class fq_codel 110:b0 parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 8us
class fq_codel 110:125 parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 3us
class fq_codel 110:155 parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 3us
class fq_codel 110:1af parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 3us
class fq_codel 110:1ca parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 196 count 0 lastcount 0 ldelay 8us
class fq_codel 110:1e5 parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 4us
class fq_codel 110:1fd parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 7us
class fq_codel 110:201 parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 9us
class fq_codel 110:20a parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 5us
class fq_codel 110:25a parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 3us
class fq_codel 110:287 parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 3us
class fq_codel 110:388 parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 228 count 0 lastcount 0 ldelay 3us
--- INGRESS ---
class htb 1:11 parent 1:1 leaf 110: prio 1 rate 32Kbit ceil 14336Kbit burst 1.56641Kb cburst 3.30859Kb 
 Sent 720 bytes 4 pkt (dropped 0, overlimits 0 requeues 0) 
 rate 0bit 0ppsbacklog 0b 0p requeues 0
 lended: 4 borrowed: 0 giants: 0
 tokens: 3570495 ctokens: 26549

class htb 1:1 root rate 43008Kbit ceil 43008Kbit burst 15.75Kb cburst 15.75Kb 
 Sent 898751332 bytes 595898 pkt (dropped 0, overlimits 0 requeues 0) 
 rate 1032Kbit 85ppsbacklog 0b 0p requeues 0
 lended: 428023 borrowed: 0 giants: 0
 tokens: 46532 ctokens: 46532

class htb 1:13 parent 1:1 leaf 130: prio 3 rate 7168Kbit ceil 42992Kbit burst 15.75Kb cburst 15.7441Kb 
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 rate 0bit 0ppsbacklog 0b 0p requeues 0
 lended: 0 borrowed: 0 giants: 0
 tokens: 281250 ctokens: 46890

class htb 1:12 parent 1:1 leaf 120: prio 2 rate 7168Kbit ceil 42992Kbit burst 15.75Kb cburst 15.7441Kb 
 Sent 900312172 bytes 596895 pkt (dropped 0, overlimits 0 requeues 0) 
 rate 1032Kbit 85ppsbacklog 0b 0p requeues 0
 lended: 167871 borrowed: 428023 giants: 0
 tokens: 279172 ctokens: 46547

class fq_codel 110:1da parent 110: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 280 count 0 lastcount 0 ldelay 2us
class fq_codel 120:20 parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 1380 count 0 lastcount 0 ldelay 7us
class fq_codel 120:c1 parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 1380 count 0 lastcount 0 ldelay 3us
class fq_codel 120:16c parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 1380 count 0 lastcount 0 ldelay 3us
class fq_codel 120:1f7 parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 688 count 0 lastcount 0 ldelay 4us
class fq_codel 120:221 parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 1380 count 0 lastcount 0 ldelay 3us
class fq_codel 120:223 parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 1380 count 0 lastcount 0 ldelay 8us
class fq_codel 120:2f2 parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 1380 count 0 lastcount 0 ldelay 9us
class fq_codel 120:31c parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 1380 count 0 lastcount 0 ldelay 4us
class fq_codel 120:32f parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 1380 count 0 lastcount 0 ldelay 4us
class fq_codel 120:3ca parent 120: 
 (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
  deficit 1260 count 0 lastcount 0 ldelay 3us

---- filter ----
--- EGRESS ---
--- INGRESS ---
filter parent 1: protocol ip pref 1 u32 
filter parent 1: protocol ip pref 1 u32 fh 801: ht divisor 1 
filter parent 1: protocol ip pref 1 u32 fh 801::800 order 2048 key ht 801 bkt 0 flowid 1:12 
  match 00000000/00fc0000 at 0
filter parent 1: protocol ip pref 2 u32 
filter parent 1: protocol ip pref 2 u32 fh 802: ht divisor 1 
filter parent 1: protocol ip pref 2 u32 fh 802::800 order 2048 key ht 802 bkt 0 flowid 1:13 
  match 00200000/00fc0000 at 0
filter parent 1: protocol ip pref 3 u32 
filter parent 1: protocol ip pref 3 u32 fh 803: ht divisor 1 
filter parent 1: protocol ip pref 3 u32 fh 803::800 order 2048 key ht 803 bkt 0 flowid 1:11 
  match 00100000/00fc0000 at 0
filter parent 1: protocol ip pref 4 u32 
filter parent 1: protocol ip pref 4 u32 fh 804: ht divisor 1 
filter parent 1: protocol ip pref 4 u32 fh 804::800 order 2048 key ht 804 bkt 0 flowid 1:11 
  match 00b00000/00fc0000 at 0
filter parent 1: protocol ip pref 5 u32 
filter parent 1: protocol ip pref 5 u32 fh 805: ht divisor 1 
filter parent 1: protocol ip pref 5 u32 fh 805::800 order 2048 key ht 805 bkt 0 flowid 1:11 
  match 00b80000/00fc0000 at 0
filter parent 1: protocol ip pref 6 u32 
filter parent 1: protocol ip pref 6 u32 fh 806: ht divisor 1 
filter parent 1: protocol ip pref 6 u32 fh 806::800 order 2048 key ht 806 bkt 0 flowid 1:11 
  match 00c00000/00fc0000 at 0
filter parent 1: protocol ip pref 7 u32 
filter parent 1: protocol ip pref 7 u32 fh 807: ht divisor 1 
filter parent 1: protocol ip pref 7 u32 fh 807::800 order 2048 key ht 807 bkt 0 flowid 1:11 
  match 00e00000/00fc0000 at 0
filter parent 1: protocol arp pref 8 u32 
filter parent 1: protocol arp pref 8 u32 fh 808: ht divisor 1 
filter parent 1: protocol arp pref 8 u32 fh 808::800 order 2048 key ht 808 bkt 0 flowid 1:11 
  match 00000000/00000000 at 0
filter parent 1: protocol all pref 999 u32 
filter parent 1: protocol all pref 999 u32 fh 800: ht divisor 1 
filter parent 1: protocol all pref 999 u32 fh 800::800 order 2048 key ht 800 bkt 0 flowid 1:12 
  match 00000000/00000000 at 8

--- MANGLE ---
Chain PREROUTING (policy ACCEPT 915K packets, 899M bytes)
 pkts bytes target     prot opt in     out     source               destination         
  148  116K DSCP       all  --  ppp1   *       0.0.0.0/0            0.0.0.0/0            DSCP match !0x00 DSCP set 0x00

Chain INPUT (policy ACCEPT 2039 packets, 419K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 913K packets, 899M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 2029 packets, 424K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 915K packets, 899M bytes)
 pkts bytes target     prot opt in     out     source               destination         
  375 28520 DSCP       all  --  *      ppp1    0.0.0.0/0            0.0.0.0/0            DSCP match !0x00 DSCP set 0x00

**Comment by pantelis86** [comment]
http://www.dslreports.com/speedtest/42600655

**Comment by negan07** [comment]
upgrade busybox to fix

`opkg update && opkg install busybox`
