### ISSUE TITLE
Country Code

### ISSUE THREAD

**Issue by gianx89** [negan07/ancistrus#61]
Hi,
there is a way to broadcast Country Code? There's a router near my flat (I'm in Europe) that's broadcasting TW country code, so I'm not able to use European 5 ghz channels on my mac.

How can I force my D7000 to broadcast IT Country Code?

Thank you in advance

**Comment by negan07** [comment]
not using apple fixed devices so can't go deep in the problem but it seems there's no other clean way to fix it apart getting rid of broken routers

read it:
https://www.howtogeek.com/211993/how-to-fix-conflicting-country-codes-and-improve-your-macs-wi-fi/

in fact TW c-codes should not be admitted inside countries like UE so they should be warned
