### ISSUE TITLE
Ancistrus #605 

### ISSUE THREAD

**Issue by MinoMuratori** [negan07/ancistrus#64]
Hi all, Hi Negan,
first of all I want to apologize for my bad English
I've been using monilitich firmware for years, today I updated to version 605 and I found a couple of small problems:
1 - the old version still appears on the ancistrus page;
2 - I updated the packages too, but continues to offer them for update.
I have attached a couple of screenshots to be clearer.

Thanks for the support and the wonderful job you do!

![D7000-1](https://user-images.githubusercontent.com/58516090/70145084-96924180-169f-11ea-910f-d6a89d4980b7.png)
![D7000](https://user-images.githubusercontent.com/58516090/70145085-96924180-169f-11ea-9b1d-6acfe1f809df.png)

**Comment by pantelis86** [comment]
clear your history of the browser

**Comment by MinoMuratori** [comment]
> clear your history of the browser

It worked!
Thank you so much for the quick reply, and sorry for the stupid question.
