### ISSUE TITLE
Cake algorithm/diffserv4 for SQM-QOS

### ISSUE THREAD

**Issue by mkexc** [negan07/ancistrus#67]
Hi,
is it possible to implement the latest and fastest algorithm in terms of SQM-QOS, namely Cake?
If you need some implementation info, look [here](https://www.bufferbloat.net/projects/codel/wiki/Cake/).
Thank you.

**Comment by negan07** [comment]
kernel version support is the key, officially included on 4.19, this is a 3.4.11 (fq_codel wasn't included too, had to patch it
the timestamp algos and some more are pretty different

https://github.com/dtaht/sch_cake

this is a standalone version out of tree of cake: 
the literature (reading some old and closed issues) doesn't show any porting attempt earlier than 3.10 kernel version without mentioning if success or not

very hard to success on it
anyway, there should be no big usage difference into this custom-partially-closed-source kernel condition...
