### ISSUE TITLE
State of the art

### ISSUE THREAD

**Issue by Jack12FR** [negan07/ancistrus#7]
Hi negan07,

Great job :)
What is the state of the art ?
I've just bought the D7000 to replace my R7000 because I wanted to have 1 box instead of my ISP modem and my R7000 router behind.
The problem is that I didn't see that no open firmware was compatible with it.
So, I would like to know if your work works and if it is stable.
In fact, I just want an other firmware than netgear's because I need to have OpenVPN on it.

Thanks in advance for your help.

Cheers,

Kévin

**Comment by negan07** [comment]
packets are stable as they run since february

**Comment by Jack12FR** [comment]
And do you think I can use an OpenVPN client with it ?

**Comment by negan07** [comment]
vpn has not been treated yet here

**Comment by negan07** [comment]
openvpn package now up
