### ISSUE TITLE
Built-in Speedtest functionality

### ISSUE THREAD

**Issue by negan07** [negan07/ancistrus#74]
Has anyone tried to use the OOKLA speedtest present into the original netgear's qos config webpage gui recently ?
Same as from console:

`speedtest
`

```
root@D7000:/$ speedtest
Prepareing test data, it will take some time...
Getting the five nearest servers
download flag = 0
can not get client info, quit now

```
It seems to be down or unavailable

**Comment by giga89** [comment]
Same here

**Comment by Linden1** [comment]
Same here too.

**Comment by negan07** [comment]
With the network-test package servers sometimes unstable too, it's safer to add an alternative.

The ookla speedtest website furnishes a speedtest tool compiled for arm arch, tested and working as standalone, but with the expense of about 1,5mb of space

**Comment by negan07** [comment]
Made a simple automate script for gui. Working from ramfs to save space.
