### ISSUE TITLE
PPP front-end package such as wvdial or ezppp Implementation

### ISSUE THREAD

**Issue by Discovery00** [negan07/ancistrus#89]
Hi negan,
I have got a question? I found pppd alternatives on linux Such as wvdial of ezppp. I think can work on D7000. Can we add ppp package different from pppd? Transmission torrent application ported successfuly by Negan07!👍🏻 Im interesting your opinions. Im waiting your response. Just a question :) I know its difficult. Thx a lot

**Comment by negan07** [comment]
replacing dialup connection breaks vendor code compatibility
can't see connection from ppp & transmission (transmission not requiring ppp connection as it can work standalone)

**Comment by Discovery00** [comment]
Okay, topic 🔒
